In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
cd drive/My\ Drive/Datasets/Challenge2

/content/drive/My Drive/Datasets/Challenge2


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.read_csv('./train.csv')
test_df = pd.read_csv('./test.csv')
sample_sub_df = pd.read_csv('./sample_submission.csv')

FileNotFoundError: ignored

In [0]:
train_df.head(10)

id  bin_0  bin_1  bin_2 bin_3 bin_4  ... ord_3 ord_4 ord_5  day month target
0   0    0.0    0.0    0.0     F     N  ...     c     U    Pw  6.0   3.0      0
1   1    1.0    1.0    0.0     F     Y  ...     e     X    pE  7.0   7.0      0
2   2    0.0    1.0    0.0     F     N  ...     n     P    eN  5.0   9.0      0
3   3    NaN    0.0    0.0     F     N  ...     a     C   NaN  3.0   3.0      0
4   4    0.0    NaN    0.0     T     N  ...     h     C    OZ  5.0  12.0      0
5   5    0.0    NaN    1.0     T     N  ...     b     Q    wa  3.0   4.0      0
6   6    0.0    0.0    0.0     F     N  ...     c     R    rg  5.0   6.0      0
7   7    0.0    0.0    1.0     T     N  ...     b     Y    PS  1.0   1.0      0
8   8    0.0    0.0    0.0     F     N  ...     c     N    mX  6.0   3.0      0
9   9    0.0    0.0    NaN     F     Y  ...     n     I    OZ  1.0   8.0      1

[10 rows x 25 columns]

In [0]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 25 columns):
id        600000 non-null int64
bin_0     582106 non-null float64
bin_1     581997 non-null float64
bin_2     582070 non-null float64
bin_3     581986 non-null object
bin_4     581953 non-null object
nom_0     581748 non-null object
nom_1     581844 non-null object
nom_2     581965 non-null object
nom_3     581879 non-null object
nom_4     581965 non-null object
nom_5     582222 non-null object
nom_6     581869 non-null object
nom_7     581997 non-null object
nom_8     582245 non-null object
nom_9     581927 non-null object
ord_0     581712 non-null float64
ord_1     581959 non-null object
ord_2     581925 non-null object
ord_3     582084 non-null object
ord_4     582070 non-null object
ord_5     582287 non-null object
day       582048 non-null float64
month     582012 non-null float64
target    600000 non-null int64
dtypes: float64(6), int64(2), object(17)
memory usage: 114.4

In [0]:
test_df.head(10)

id  bin_0  bin_1  bin_2 bin_3  ... ord_3 ord_4 ord_5  day month
0  600000    0.0    0.0    0.0     F  ...     f     U    oU  3.0   9.0
1  600001    0.0    0.0    0.0     F  ...     n     N   NaN  2.0   8.0
2  600002    0.0    0.0    0.0     F  ...     i     N    DN  2.0   6.0
3  600003    1.0    0.0    0.0     F  ...     m     B    AG  1.0   6.0
4  600004    0.0    0.0    1.0     F  ...     o     J    DT  3.0   3.0
5  600005    0.0    0.0    0.0   NaN  ...     e     Y    th  5.0   6.0
6  600006    0.0    0.0    0.0     F  ...     n     U    RD  1.0   6.0
7  600007    0.0    0.0    1.0     F  ...     f   NaN    pT  2.0   6.0
8  600008    0.0    0.0    0.0     T  ...     c     Y    nj  5.0   5.0
9  600009    0.0    0.0    0.0     F  ...     k     M    dp  7.0   2.0

[10 rows x 24 columns]

In [0]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 24 columns):
id       400000 non-null int64
bin_0    388099 non-null float64
bin_1    387962 non-null float64
bin_2    388028 non-null float64
bin_3    388049 non-null object
bin_4    388049 non-null object
nom_0    387938 non-null object
nom_1    388053 non-null object
nom_2    387821 non-null object
nom_3    387824 non-null object
nom_4    388007 non-null object
nom_5    388088 non-null object
nom_6    387988 non-null object
nom_7    387997 non-null object
nom_8    388044 non-null object
nom_9    387940 non-null object
ord_0    388107 non-null float64
ord_1    387833 non-null object
ord_2    387895 non-null object
ord_3    387947 non-null object
ord_4    388067 non-null object
ord_5    387953 non-null object
day      387975 non-null float64
month    388016 non-null float64
dtypes: float64(6), int64(1), object(17)
memory usage: 73.2+ MB


In [0]:
# summary of numerical data
train_df.describe(include=np.number)

id          bin_0  ...          month         target
count  600000.000000  582106.000000  ...  582012.000000  600000.000000
mean   299999.500000       0.092301  ...       6.371317       0.187205
std    173205.225094       0.289451  ...       3.458959       0.390076
min         0.000000       0.000000  ...       1.000000       0.000000
25%    149999.750000       0.000000  ...       3.000000       0.000000
50%    299999.500000       0.000000  ...       6.000000       0.000000
75%    449999.250000       0.000000  ...       8.000000       0.000000
max    599999.000000       1.000000  ...      12.000000       1.000000

[8 rows x 8 columns]

In [0]:
# summary of categorical data
train_df.describe(include=np.object)

bin_3   bin_4   nom_0     nom_1  ...     ord_2   ord_3   ord_4   ord_5
count   581986  581953  581748    581844  ...    581925  582084  582070  582287
unique       2       2       3         6  ...         6      15      26     190
top          F       N     Red  Triangle  ...  Freezing       n       N      Fl
freq    366212  312344  323286    164190  ...    142726   70982   39978   10562

[4 rows x 17 columns]

In [0]:
# df labels
labels = [col for col in train_df.columns if col != 'target']
print(f'df labels: {labels}')

df labels: ['id', 'bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1', 'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9', 'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month']


In [0]:
# drop unwanted columns
combined = [train_df, test_df]
unwanted = ['nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9']
for df in combined:
  for title in unwanted:
    df.drop(title, axis=1, inplace=True)
    
train_df.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4  ... ord_3 ord_4 ord_5  day month  target
0   0    0.0    0.0    0.0     F     N  ...     c     U    Pw  6.0   3.0       0
1   1    1.0    1.0    0.0     F     Y  ...     e     X    pE  7.0   7.0       0
2   2    0.0    1.0    0.0     F     N  ...     n     P    eN  5.0   9.0       0
3   3    NaN    0.0    0.0     F     N  ...     a     C   NaN  3.0   3.0       0
4   4    0.0    NaN    0.0     T     N  ...     h     C    OZ  5.0  12.0       0

[5 rows x 20 columns]

In [0]:
# fill NaN with 0s in bin_0 and bin_1 due to high percentage of 0s
train_df[['bin_0', 'bin_1']].describe(percentiles=[.775, .8, .85, .9], include=np.number)

bin_0          bin_1
count  582106.000000  581997.000000
mean        0.092301       0.185532
std         0.289451       0.388729
min         0.000000       0.000000
50%         0.000000       0.000000
77.5%       0.000000       0.000000
80%         0.000000       0.000000
85%         0.000000       1.000000
90%         0.000000       1.000000
max         1.000000       1.000000

In [0]:
test_df[['bin_0', 'bin_1']].describe(percentiles=[.775, .8, .85, .9], include=np.number)

bin_0          bin_1
count  388099.000000  387962.000000
mean        0.093590       0.187155
std         0.291257       0.390036
min         0.000000       0.000000
50%         0.000000       0.000000
77.5%       0.000000       0.000000
80%         0.000000       0.000000
85%         0.000000       1.000000
90%         0.000000       1.000000
max         1.000000       1.000000

In [1]:
# forward fill null entries
for df in combined:
  df.fillna(method='bfill', inplace=True)

train_df.info()

NameError: ignored

In [0]:
# nom_0 - nom_4 categorical encoding
for c in ['nom_0', 'nom_1', 'nom_2', 'nom_3', 'nom_4']:
  print(f'train_df[{c}]: {pd.unique(train_df[c])}')

train_df[nom_0]: ['Red' 'Blue' 'Green']
train_df[nom_1]: ['Trapezoid' 'Star' 'Circle' 'Triangle' 'Polygon' 'Square']
train_df[nom_2]: ['Hamster' 'Axolotl' 'Lion' 'Dog' 'Cat' 'Snake']
train_df[nom_3]: ['Russia' 'Canada' 'Finland' 'Costa Rica' 'China' 'India']
train_df[nom_4]: ['Bassoon' 'Theremin' 'Oboe' 'Piano']


In [0]:
# ord_1 - ord_5 normal encoding
ords = ['ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4']
for category in ords:
  print(train_df[category].value_counts())

1.0    235111
3.0    204021
2.0    160868
Name: ord_0, dtype: int64
Novice         165535
Expert         143883
Contributor    113294
Grandmaster     98912
Master          78376
Name: ord_1, dtype: int64
Freezing       147133
Warm           128080
Cold           100761
Boiling Hot     87547
Hot             69565
Lava Hot        66914
Name: ord_2, dtype: int64
n    73170
a    67390
m    59737
c    58456
h    57456
o    46805
b    46201
e    40126
k    39928
i    35796
d    31569
f    30337
g     6365
j     3755
l     2909
Name: ord_3, dtype: int64
N    41207
P    39047
Y    37797
A    37745
R    34004
U    33918
M    33523
X    33374
C    33087
H    32118
Q    31069
T    30664
O    26417
B    25999
E    22610
K    22282
I    20405
D    17838
F    17251
W     8545
Z     5951
S     4739
G     3505
V     3194
J     1999
L     1712
Name: ord_4, dtype: int64


In [0]:
encode_labels = ['bin_3', 'bin_4', 'nom_0', 'nom_1', 'nom_2', 'nom_3', 'nom_4', 'ord_1', 'ord_2', 
                 'ord_3', 'ord_4', 'ord_5']
encode = []
for c in encode_labels:
  encode.append(dict((ty, num) for num, ty in enumerate(pd.unique(train_df[c]))))

In [0]:
for c, en in zip(encode_labels, encode):
  train_df[c] = train_df[c].apply(lambda x:en[x])
  test_df[c] = test_df[c].apply(lambda x:en[x])

train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 20 columns):
id        600000 non-null int64
bin_0     600000 non-null float64
bin_1     600000 non-null float64
bin_2     600000 non-null float64
bin_3     600000 non-null int64
bin_4     600000 non-null int64
nom_0     600000 non-null int64
nom_1     600000 non-null int64
nom_2     600000 non-null int64
nom_3     600000 non-null int64
nom_4     600000 non-null int64
ord_0     600000 non-null float64
ord_1     600000 non-null int64
ord_2     600000 non-null int64
ord_3     600000 non-null int64
ord_4     600000 non-null int64
ord_5     600000 non-null int64
day       600000 non-null float64
month     600000 non-null float64
target    600000 non-null int64
dtypes: float64(6), int64(14)
memory usage: 91.6 MB


In [0]:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

<h2>Logistic Regression Model</h2>

In [0]:
x_train = train_df.drop('target', 1).drop('id', 1).values
y_train = train_df['target'].values 

In [0]:
clf = LogisticRegression(solver='liblinear')
cv_results = cross_validate(clf, x_train, y_train)

In [0]:
cv_results['test_score']

array([0.81270833, 0.81269167, 0.81295833, 0.81284167, 0.812875  ])

In [0]:
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

<h2>Submission</h2>

In [0]:
x_test = test_df.drop('id', 1).values

In [0]:
y_hat = clf.predict_proba(x_test)
print(y_hat[0:5])

[[0.67056209 0.32943791]
 [0.81558131 0.18441869]
 [0.81786762 0.18213238]
 [0.92412642 0.07587358]
 [0.84682329 0.15317671]]


In [0]:
submission_lgr = pd.DataFrame()
submission_lgr['id'] = test_df['id']
submission_lgr['target'] = y_hat[:, 1]
submission_lgr.head(10)

id    target
0  600000  0.329438
1  600001  0.184419
2  600002  0.182132
3  600003  0.075874
4  600004  0.153177
5  600005  0.212635
6  600006  0.237168
7  600007  0.226818
8  600008  0.166150
9  600009  0.123319

In [0]:
submission_lgr.to_csv('./lgr_predictions.csv') 

<h2> Random Forest Model</h2>

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
tree = RandomForestClassifier()
tree.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_hat = tree.predict_proba(x_test)
print(y_hat[0:5])

[[0.73 0.27]
 [0.83 0.17]
 [0.85 0.15]
 [0.82 0.18]
 [0.74 0.26]]


In [0]:
submission_rf = pd.DataFrame()
submission_rf['id'] = test_df['id']
submission_rf['target'] = y_hat[:, 1]
submission_rf.head(10)

id  target
0  600000    0.27
1  600001    0.17
2  600002    0.15
3  600003    0.18
4  600004    0.26
5  600005    0.31
6  600006    0.48
7  600007    0.31
8  600008    0.15
9  600009    0.22

In [0]:
submission_rf.to_csv('./rf_predictions.csv') 